In [1]:
import pandas as pd
import numpy as np
#from dataprep.datasets import load_dataset   # Used to import / load dataset
#from dataprep.eda import create_report   # Used to load Report formate

In [2]:
df=pd.read_csv(r'C:\Users\Zohaib\OneDrive\Documents\MachineLearning\5_features_extracted.csv', index_col=['Datetime'], parse_dates=['Datetime'])
df.head()

,aep,year_day,holiday,weekend,winter,spring,summer,fall,hour,month,day_of_week
Datetime,,,,,,,,,,,
2004-10-01 01:00:00,12379.0,275,0,0,0,0,0,1,1,10,4
2004-10-01 02:00:00,11935.0,275,0,0,0,0,0,1,2,10,4
2004-10-01 03:00:00,11692.0,275,0,0,0,0,0,1,3,10,4
2004-10-01 04:00:00,11597.0,275,0,0,0,0,0,1,4,10,4
2004-10-01 05:00:00,11681.0,275,0,0,0,0,0,1,5,10,4

In [3]:
print('pearson\n\n',df.corrwith(df["aep"],method="pearson"))

pearson

 aep            1.000000
year_day      -0.124617
holiday       -0.053212
weekend       -0.267287
winter         0.328332
spring        -0.246582
summer         0.139793
fall          -0.220913
hour           0.421008
month         -0.125896
day_of_week   -0.220016
dtype: float64

In [4]:
print('kendall\n\n',df.corrwith(df["aep"],method="kendall"))

kendall

 aep            1.000000
year_day      -0.082592
holiday       -0.041101
weekend       -0.218066
winter         0.278561
spring        -0.197749
summer         0.098140
fall          -0.178467
hour           0.292545
month         -0.085584
day_of_week   -0.158129
dtype: float64

In [5]:
print('spearman\n\n',df.corrwith(df["aep"],method="spearman"))

spearman

 aep            1.000000
year_day      -0.123249
holiday       -0.050335
weekend       -0.267060
winter         0.341147
spring        -0.242178
summer         0.120189
fall          -0.218564
hour           0.431821
month         -0.123443
day_of_week   -0.219619
dtype: float64

In [6]:
df.isnull().sum()

aep            0
year_day       0
holiday        0
weekend        0
winter         0
spring         0
summer         0
fall           0
hour           0
month          0
day_of_week    0
dtype: int64

In [29]:
weekend_2006 = df[(df.index.year == 2006) & (df["day_of_week"] == 1)]

weekend_2006[["aep"]]

                         aep
Datetime
2006-01-03 00:00:00  14333.0
2006-01-03 01:00:00  13650.0
2006-01-03 02:00:00  13392.0
2006-01-03 03:00:00  13112.0
2006-01-03 04:00:00  13147.0
...                      ...
2006-12-26 19:00:00  17769.0
2006-12-26 20:00:00  17600.0
2006-12-26 21:00:00  17387.0
2006-12-26 22:00:00  17019.0
2006-12-26 23:00:00  16298.0

[1248 rows x 1 columns]

In [30]:
weekend_2006["aep"].mean()

np.float64(16371.711538461539)

In [31]:
weekend_2006["aep"].sum()

np.float64(20431896.0)

In [26]:
weekend_2006["aep"].max()

np.float64(22520.0)

In [15]:
weekend_2006["aep"].min()

np.float64(10176.0)

In [16]:
weekend_2006.groupby("hour")["aep"].mean()

hour
0     14454.561905
1     13627.352381
2     13121.400000
3     12835.771429
4     12696.447619
5     12707.733333
6     12932.285714
7     13297.133333
8     13819.085714
9     14492.228571
10    14961.676190
11    15164.123810
12    15238.161905
13    15270.790476
14    15241.438095
15    15165.095238
16    15170.523810
17    15343.142857
18    15720.152381
19    15952.380952
20    16014.780952
21    16023.161905
22    15838.142857
23    15160.095238
Name: aep, dtype: float64

In [35]:
df.groupby("day_of_week")["aep"].mean()

day_of_week
0    15803.722241
1    16049.878463
2    16005.778018
3    16017.463750
4    15765.769918
5    14610.685596
6    14199.639370
Name: aep, dtype: float64